version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: sky-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: sky_takeout
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password"
      ]
    volumes:
      - sky-mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: sky-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - sky-redis-data:/data

volumes:
  sky-mysql-data:
  sky-redis-data:

